# HackerNews Database.

In [0]:
# import pandas.
import pandas as pd

In [66]:
# load the csv files.
db1 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb1.csv')
db2 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb2.csv')
db3 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb3.csv')
db4 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb4.csv')
db9 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb9.csv')
db10 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb10.csv')
db11 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb11.csv')
db12 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb12.csv')
db13 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb13.csv')
db14 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb14.csv')
db15 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb15.csv')
db16 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb16.csv')
db17 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb17.csv')
db18 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb18.csv')
db19 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb19.csv')
db20 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb20.csv')
db21 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb21.csv')
db22 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb22.csv')
db23 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb23.csv')
db24 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb24.csv')
db25 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb25.csv')
db26 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb26.csv')
db27 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb27.csv')
db28 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb28.csv')
db29 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb29.csv')
db30 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb30.csv')
db31 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb31.csv')
db32 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb32.csv')
db33 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb33.csv')
db34 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb34.csv')
db35 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb35.csv')
db36 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb36.csv')
db37 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb37.csv')
db38 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb38.csv')
db39 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb39.csv')
db40 = pd.read_csv('https://raw.githubusercontent.com/CVanchieri/DataSets/master/HackerNews/commentsdb40.csv')
# merge the csv files.
HNfinalDB = pd.concat([db1, db2, db3, db4, db9, db10, db11, db12, db13, db14, db15, db16, 
                       db17, db18, db19, db20, db21, db22, db23, db24, db25, db26, db27, 
                       db28, db29, db30, db31, db32, db33, db34, db35, db36, db37, db38, 
                       db39, db40], sort=True)
# drop unecessary columns.
HNfinalDB = HNfinalDB.drop(columns=['dead', 'deleted', 'parent', 'time'])
# use datetime on time_ts column.
HNfinalDB['time_ts'] = pd.to_datetime(HNfinalDB['time_ts'], infer_datetime_format=True)
# seperate the date and time from time_ts column.
HNfinalDB['date'] = [d.date() for d in HNfinalDB['time_ts']]
HNfinalDB['time'] = [d.time() for d in HNfinalDB['time_ts']]
# sepereate the year, month, day for date column.
HNfinalDB['year'] = HNfinalDB['date'].map(lambda x: x.year)
HNfinalDB['month'] = HNfinalDB['date'].map(lambda x: x.month)
HNfinalDB['day'] = HNfinalDB['date'].map(lambda x: x.day)
# drop the time_ts column.
HNfinalDB = HNfinalDB.drop(columns=['time_ts', 'date'])
# reorganize the columns.
HNfinalDB = HNfinalDB[['year', 'month', 'day', 'time', 'author', 'id', 'text', 'ranking']]
# drop any duplicate columns based on id column.
HNfinalDB.drop_duplicates(subset ="id", keep = "first", inplace = True)
# show data frame shape.
print(HNfinalDB.shape)
# show the data frame with headers.
HNfinalDB.head(10)

(217824, 8)

   year  month  ...                                               text ranking
0  2013     11  ...  Bitcoin is only valuable because it can be con...       0
1  2013     12  ...  Came in here to make this exact comment -- the...       0
2  2014      5  ...  So I think you might be excluding people that ...       0
3  2009     11  ...  There seems to be a slight difference in that ...       0
4  2010      6  ...  Point I didn't get to make: learn how to filte...       0
5  2010      2  ...  i wouldnt do it via webcam, thats just a big b...       0
6  2011      5  ...  That really doesn't make any sense. As anyone ...       0
7  2011     10  ...  Learning from books by yourself is one of the ...       0
8  2012      9  ...  Incredible, period. Some pictures for everyone...       0
9  2015      7  ...  It&#x27;s a great question.<p>GitLab is open s...       0

[10 rows x 8 columns]

In [67]:
# authors with the most comments in the database.
HNtop = HNfinalDB['author'].value_counts()[:10].sort_values(ascending=False)
print("--authors with most comments--")
print(HNtop)

--authors with most comments--
DanBC          446
sp332          440
davidw         429
eru            399
pg             363
Tichy          363
gaius          343
wmf            317
sliverstorm    311
jerf           308
Name: author, dtype: int64

# Data filtered by 'year'.

In [56]:
# check the data range on the year column.
HNfinalDB.year.value_counts()

2013    43248
2014    39478
2015    32372
2012    32147
2011    27146
2010    22134
2009    12662
2008     6629
2007     2008
Name: year, dtype: int64

In [69]:
# seperate data on 'year' column.
is2007 =  HNfinalDB['year']==2007
HN2007 = HNfinalDB[is2007]
HN2007 = HN2007['author'].value_counts()[:10].sort_values(ascending=False)
is2008 =  HNfinalDB['year']==2008
HN2008 = HNfinalDB[is2008]
HN2008 = HN2008['author'].value_counts()[:10].sort_values(ascending=False)
is2009 =  HNfinalDB['year']==2009
HN2009 = HNfinalDB[is2009]
HN2009 = HN2009['author'].value_counts()[:10].sort_values(ascending=False)
is2010 =  HNfinalDB['year']==2010
HN2010 = HNfinalDB[is2010]
HN2010 = HN2010['author'].value_counts()[:10].sort_values(ascending=False)
is2011 =  HNfinalDB['year']==2011
HN2011 = HNfinalDB[is2011]
HN2011 = HN2011['author'].value_counts()[:10].sort_values(ascending=False)
is2012 =  HNfinalDB['year']==2012
HN2012 = HNfinalDB[is2012]
HN2012 = HN2012['author'].value_counts()[:10].sort_values(ascending=False)
is2013 =  HNfinalDB['year']==2013
HN2013 = HNfinalDB[is2013]
HN2013 = HN2013['author'].value_counts()[:10].sort_values(ascending=False)
is2014 =  HNfinalDB['year']==2014
HN2014 = HNfinalDB[is2014]
HN2014 = HN2014['author'].value_counts()[:10].sort_values(ascending=False)
is2015 =  HNfinalDB['year']==2015
HN2015 = HNfinalDB[is2015]
HN2015 = HN2015['author'].value_counts()[:10].sort_values(ascending=False)
# show the top results for each year.
print("--2007 authors with most comments--")
print(HN2007)
print("--2008 authors with most comments--")
print(HN2008)
print("--2009 authors with most comments--")
print(HN2009)
print("--2010 authors with most comments--")
print(HN2010)
print("--2011 authors with most comments--")
print(HN2011)
print("--2012 authors with most comments--")
print(HN2012)
print("--2013 authors with most comments--")
print(HN2013)
print("--2014 authors with most comments--")
print(HN2014)
print("--2015 authors with most comments--")
print(HN2015)

--2007 authors with most comments--
rms             76
pg              58
Tichy           37
davidw          36
nickb           22
nostrademons    21
danw            21
palish          21
juwo            19
brlewis         19
Name: author, dtype: int64
--2008 authors with most comments--
pg        73
davidw    67
edw519    67
Tichy     65
rms       60
axod      50
hugh      46
yters     43
eru       42
gaius     41
Name: author, dtype: int64
--2009 authors with most comments--
axod       91
davidw     77
pg         73
mahmud     72
eru        71
gaius      67
ErrantX    57
vaksel     56
Tichy      56
anamax     55
Name: author, dtype: int64
--2010 authors with most comments--
eru       119
hga       102
hugh3      89
Groxx      89
Tichy      78
ugh        70
anamax     70
mahmud     66
pyre       64
btilly     63
Name: author, dtype: int64
--2011 authors with most comments--
hugh3            86
sp332            70
ugh              67
jerf             61
chc              58
sliverstorm      53
wccrawford       52
gaius            50
nextparadigms    47
InclinedPlane    46
Name: author, dtype: int64
--2012 authors with most comments--
rdl       89
DanBC     89
sp332     83
ajross    63
rmc       61
mtgx      60
Evbn      57
ktizo     56
btilly    54
untog     53
Name: author, dtype: int64
--2013 authors with most comments--
DanBC          138
mpyne          123
lutusp         102
rdl            102
sliverstorm     90
sp332           88
VLM             82
pjmlp           81
vacri           73
coldtea         71
Name: author, dtype: int64
--2014 authors with most comments--
dang             143
baddox           110
DanBC            103
pjmlp            100
bane              96
sp332             90
dragonwriter      79
higherpurpose     70
icebraining       61
lutusp            60
Name: author, dtype: int64
--2015 authors with most comments--
dang             143
DanBC             95
dragonwriter      86
pjmlp             82
sp332             65
hga               61
Animats           61
pjc50             59
Retric            53
nickpsecurity     52
Name: author, dtype: int64